import type { TrainingLesson } from '@swasthya/shared-types';
export const trainingLessons: readonly TrainingLesson[] = [
  { id: 'meet-sathi', titleNe: 'स्वास्थ्य साथीलाई चिन्नुहोस्', titleEn: 'Meet your health companion', durationSeconds: 52, posterKey: 'meet-sathi', transcriptNe: 'साथीले तपाईंको स्वास्थ्य प्रश्न बुझ्न, सुरक्षित अर्को कदम छान्न र आवश्यक परे स्वास्थ्यकर्मीसँग जोड्न मद्दत गर्छ। साथी डाक्टर होइन र निदान वा औषधि लेख्दैन।', transcriptEn: 'Sathi helps understand your question, choose a safe next step, and connect you with a health professional when needed. Sathi is not a doctor and does not diagnose or prescribe.', reviewStatus: 'DRAFT', version: 1 },
  { id: 'build-twin', titleNe: 'स्वास्थ्य चित्र एक–एक कदममा', titleEn: 'Build your health picture step by step', durationSeconds: 68, posterKey: 'build-twin', transcriptNe: 'हरेक जानकारी किन उपयोगी छ भन्ने पहिले देखाइन्छ। तपाईं उत्तर दिन, छोड्न वा पछि सच्याउन सक्नुहुन्छ। तपाईंको अनुमति बिना नयाँ जानकारी डाक्टर वा संस्थासँग साझा हुँदैन।', transcriptEn: 'You see why each detail is useful before answering. You can answer, skip, or correct it later. New information is not shared without permission.', reviewStatus: 'DRAFT', version: 1 },
  { id: 'emergency', titleNe: 'आपतकालमा के गर्ने', titleEn: 'What to do in an emergency', durationSeconds: 44, posterKey: 'emergency', transcriptNe: 'आपतकालीन संकेत देखिएमा सामान्य कुराकानी रोकिन्छ। एपले उपचार गर्दैन। प्रमाणित स्थानीय सेवामा सम्पर्क गर्नुहोस् वा नजिकको उपयुक्त अस्पताल जानुहोस्।', transcriptEn: 'When warning signs appear, normal conversation stops. The app does not provide emergency treatment. Contact a verified local service or go to the nearest appropriate hospital.', reviewStatus: 'CLINICAL_REVIEW', version: 1 },
  { id: 'share-care', titleNe: 'जानकारी सुरक्षित रूपमा साझा गर्नुहोस्', titleEn: 'Share information safely', durationSeconds: 61, posterKey: 'share-care', transcriptNe: 'कुन जानकारी, कसलाई र कति समयका लागि दिने भन्ने तपाईंले छान्नुहुन्छ। भविष्यको पहुँच फिर्ता लिन सकिन्छ र पहुँच इतिहास हेर्न सकिन्छ।', transcriptEn: 'You choose what to share, with whom, and for how long. Future access can be revoked and access history remains visible.', reviewStatus: 'DRAFT', version: 1 },
];
export function playableLessons(): TrainingLesson[] {
  return trainingLessons.filter((lesson) => lesson.reviewStatus === 'APPROVED' && Boolean(lesson.streamUrl));
}
